dependencies:
  - aave/protocol-v2@1.0.1
#  # - <organization/repo>@<version>
#  - smartcontractkit/chainlink-brownie-contracts@1.1.1
#  - OpenZeppelin/openzeppelin-contracts@3.4.0
compiler:
  solc:
    remappings:
      - '@aave=aave/protocol-v2@1.0.1'
#      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
#      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
dotenv: .env
settings:
  gas_limit: "100000000000"
wallets:
  from_key: ${PRIVATE_KEY}
networks:
  default: mainnet-fork
  kovan:
    dai_token: '0xFf795577d9AC8bD7D90Ee22b6C1703490b6512FD'
    weth_token: '0xd0A1E359811322d97991E03f863a0C30C2cF029C'
    lending_pool_addresses_provider: '0x88757f2f99175387ab4c6a4b3067c77a695b0349'
    dai_eth_price_feed: '0x22B58f1EbEDfCA50feF632bD73368b2FdA96D541'
  mainnet-fork:
    dai_token: "0x6B175474E89094C44Da98b954EedeAC495271d0F"
    lending_pool_addresses_provider_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    weth_token: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
    lending_pool_addresses_provider: '0xb53c1a33016b2dc2ff3653530bff1848a515c8c5'
    verify: False
    dai_eth_price_feed: '0x773616E4d11A78F511299002da57A0a94577F1f4'
